### ISSUE TITLE
Windows 8 Support?

### ISSUE THREAD

**Issue by NetOpWibby** [ColemanGariety/galileo#11]
I installed Galileo and then saw this error message when I tried to run it.

![screenshot_44](https://f.cloud.github.com/assets/1288356/2172319/959b3344-9591-11e3-87cc-957e7b38a1e6.png)

**Comment by ColemanGariety** [comment]
Ah I know what's causing this. Can you run `gem env` to find your gem bind path, and edit the `bin/galileo` file within the galileo gem to include this line at the top:

```
# encoding: utf-8
```

If that fixes your issue I'll fix it and push to rubygems.

**Comment by NetOpWibby** [comment]
Unfortunately, this didn't work. I added that line to several galileo files, and them removed it when nothing changed.

– Paul Anthony Webb

**Comment by ColemanGariety** [comment]
@NetOperatorWibby push 0.2.1 to rubygems, would you mind reinstalling the gem and trying again?
