### ISSUE TITLE
Search my repos.

### ISSUE THREAD

**Issue by lukasoppermann** [ColemanGariety/galileo#4]
Hey, could you include repos I created but did not star?

**Comment by ColemanGariety** [comment]
@lukasoppermann isn't it common to star ones own repos?

If not—sure, easy fix, but I'd like to hear @colbyaley's input on this.

**Comment by cp** [comment]
@JacksonGariety I think what he means is that he would like to search his own repos. I could see this being useful if you're like me and Fork & Forget™ repos far too often.

Technically, it would be just one more API call that could probably be cached with the others.

**Comment by ColemanGariety** [comment]
@ColbyAley yes but if you star all your own repos they appear in results anyway.

**Comment by lukasoppermann** [comment]
Hey, I don't know whether its common, but I hardly ever do it, since they are in my list anyway. :) Especially the above mentioned forks.
