### ISSUE TITLE
Faraday::Builder is now Faraday::RackBuilder

### ISSUE THREAD

**Issue by morganestes** [ColemanGariety/galileo#5]
When I run `galileo`, the message `Faraday::Builder is now Faraday::RackBuilder.` is printed before the table each time.

**Comment by ColemanGariety** [comment]
That's odd, since Galileo no longer uses Faraday as a dependency. I'd say the most likely scenario is that this is a bug with your installed version of Octokit, which depends upon Faraday.

**Comment by morganestes** [comment]
The only version of Octokit I have is the one that was installed with Galileo.
Here's what I have installed:

```
*** LOCAL GEMS ***

addressable (2.3.5)
api_cache (0.2.3)
bigdecimal (1.2.5, 1.2.4, 1.2.3)
bropages (0.0.15)
bundler (1.5.2, 1.5.1)
bundler-unload (1.0.2)
colorize (0.6.0)
commander (4.1.5)
executable-hooks (1.3.1, 1.3.0, 1.2.6)
faraday (0.9.0)
galileo (0.1.1)
gem-wrappers (1.2.4, 1.2.1)
haste (0.1.7)
highline (1.6.20)
io-console (0.4.2)
json (1.8.1)
json_pure (1.8.1)
localtunnel (0.3)
mime-types (2.1)
minitest (5.2.2, 5.2.1, 5.2.0, 4.7.5)
moneta (0.7.20)
multipart-post (2.0.0)
net-ssh (2.7.0)
net-ssh-gateway (1.2.0)
netrc (0.7.7)
octokit (2.7.0)
psych (2.0.2)
rake (10.1.1, 10.1.0)
rdoc (4.1.1, 4.1.0)
rest-client (1.6.7)
rubygems-bundler (1.4.2)
rvm (1.11.3.9, 1.11.3.8)
sawyer (0.5.3)
smart_colored (1.1.1)
test-unit (2.5.5, 2.1.0.0)
```

**Comment by morganestes** [comment]
Yup, updated all my gems (including octokit) and I'm back in business. Thanks!

**Comment by ColemanGariety** [comment]
@morganestes it might've been an isolated bug in Octokit. I'll lock down the versions on the dependencies so that this doesn't happen again.
